apiVersion: v1
kind: ConfigMap
metadata:
  name: wiremock-stubs
  labels:
    app: wiremock
data:
  example.json: |
    {
      "request": {
        "method": "GET",
        "url": "/example"
      },
      "response": {
        "status": 200,
        "body": "{{request.path.[0]}}",
        "headers": {
          "Content-Type": "text/plain"
        },
        "transformers": ["response-template", "com.dfs.StringManipulationTransfromer"]
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiremock-jars
  labels:
    app: wiremock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  labels:
    app: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
    spec:
      volumes:
      - name: wiremock-jars
        persistentVolumeClaim:
          claimName: wiremock-jars
      - name: stubs-volume
        configMap:
          name: wiremock-stubs
      containers:
      - name: wiremock
        image: registry.redhat.io/ubi8/openjdk-11:latest
        command: ["java"]
        args: ["-cp", "/opt/wiremock/wiremock-standalone.jar:/opt/wiremock/custom-wiremock-transformer.jar", "com.github.tomakehurst.wiremock.standalone.WiremockServerRunner", "--extensions", "com.dfs.StringManipulationTransfromer", "--global-response-templating", "--root-dir", "/opt/wiremock/mappings"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /__admin/
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: wiremock-jars
          mountPath: /opt/wiremock
        - name: stubs-volume
          mountPath: /opt/wiremock/mappings
---
apiVersion: v1
kind: Service
metadata:
  name: wiremock
  labels:
    app: wiremock
spec:
  selector:
    app: wiremock
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wiremock
  labels:
    app: wiremock
spec:
  to:
    kind: Service
    name: wiremock
  port:
    targetPort: http 